services:
  - type: web
    name: cinecove
    env: node
    plan: free
    buildCommand: npm ci && npx vite build
    startCommand: npm run dev
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: cinecove-db
          property: connectionString
      - key: TMDB_API_KEY
        sync: false
    region: oregon

databases:
  - name: cinecove-db
    databaseName: cinecove
    user: cinecove
    plan: free